title: VirtualLife - roleplaying game
email: your-email@domain.com
description: The blog to the VirtualLife game.

baseurl: "/"
url: http://keralahost.in/virtuallife
google_adsense: Your-adsense-code

markdown: kramdown

name: VirtualLife - roleplaying game

date: 2019-05-03 19:57:37 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/virtuallife
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: 
